### PR TITLE
Add smartctl device path and parameter override via smart.json configuration for RAID controllers

### PR DESCRIPTION
**Pull request by ArakniD**
## Pull Request Checklist

Adding device path & parameter override to allow smartctl access to 3ware (and other) RAID controller. Added this to check-smart.rb and check-smart-status.rb.

Also added an ignore attribute option to explicitly ignore attributes with yakky values. My intel 520 is reporting massive uncorrected inputs but is actually fine. Other users (on google search) have reported 
the same issue with this SSD.
#48
#### General
- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [X] Update README with any necessary configuration snippets
#### Known Compatablity Issues

Not tested against any other RAID controller but it 'should' work given that the link below states fairly similar parameter configuration.

Smartctl RAID paramteres(https://www.smartmontools.org/wiki/Supported_RAID-Controllers)

### CODE REVIEW

**Comment by majormoses** [comment]
could you fix the tests and rebase?

**Comment by majormoses** [comment]
@ArakniD just checking if you plan on workin on this or if I should close this out.

**Comment by ArakniD** [comment]
I do actually. I'll refresh my memory tomorrow night and update

**Comment by ArakniD** [comment]
I'll check this back on my running system against the new paths. I hope I resolved this correctly..

**Comment by majormoses** [comment]
ping @ArakniD

**Comment by ArakniD** [comment]
Sorry I thought I had uploaded this already!

Ok I can commit this via the web :)

**Comment by majormoses** [comment]
any chance you could fix up the linting?

**Comment by ArakniD** [comment]
Yup. Home soon.

**Comment by majormoses** [comment]
@ArakniD I applaud the valiant effort, if you want to give me access to your fork I can fix it up for you.

**Comment by ArakniD** [comment]
hehe :) That maybe best. Roby and Github are not my cup of tea.

**Comment by majormoses** [comment]
It looks like you got it working I had just come back here to clone it and it looked good after your last commit.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-disk-checks/versions/2.4.0

**Pull request merged**
